# We need an OSX agent. This is a bit slow, but that's the only system that can properly cross-compile appix for all
# three environments.
os: osx

language: go

go:
- tip # The latest version of Go.

script:
- "./build.sh"

deploy:
  provider: releases
  skip_cleanup: true # Important, otherwise the build output would be purged.
  api_key:
    secure: ayjnbXT7shzNJ+sV8szbPinTkVGQxS3abtOUASEpu7yR0IhX2SSUNoM0/TENIToCsgD4guTn9RpUsL7RFrlO3sXZjobK/gmgiM/XfsLOPhZrV4f4iRbi552su8FtkQY5nYTfIzPHE55Pymw0hiKO9TB9rw/UNdz4w+EIQ3limTi6BHLMDjyhJMYxsgOIbsOXQ6hFsg21Owrhn+IS2QJovdmx52UEuqE85X8002cta0oxzz7j3hs7h+qiPbAXbuP8s0i1S/2x55BJ2K3PEUkf3JVmOOxX/dt/5XJ+7DR7UYz8zwCCEphyeARNpfX8LCiJtKQfp6/o+1o06GWkGlSVLymAmPGF/R1kD5mxb56wC8yGypt2hq2EcxUELS5bmARj3BB5O1R8xCTF817aaabM3paSovDiHuRuFtpPp2Kb9enoZasH/P+j83dhmmq6k/uaIearKS085KMyiGJUq3Rdr2CYD0nZDay5NgrN+h5OPhLtSB1Vk6I6SEHftJxWXua0bP3Ks6KN7m1TP6jEwKJrr8SU97FTzRiHw+o3YYISCyAdJnvgx3LEXN5l7S1eEQSZqbdMipbnvTqcBlLOJa6G4oK880ipq+lxDvSmPYxV4jRyI+9szNK2NSrqgOVmbwCwQvoVFKcCKlvzETtdePrLRYPvoaeKJx8XF4bTawJmHMw=
  file:
    - bin/appix-mac
    - bin/appix-linux
    - bin/appix.exe
  on:
    repo: Travix-International/appix
    tags: true # The deployment happens only if the commit has a tag.

notifications:
  email: false
