# We need an OSX agent. This is a bit slow, but that's the only system that can properly cross-compile appix for all
# three environments.
os: osx

language: go

go:
- tip # The latest version of Go.

script:
- "./build.sh"

deploy:
  provider: releases
  skip_cleanup: true # Important, otherwise the build output would be purged.
  api_key:
    secure: "O+o6TvXPt6PFohWwTLLOlmH98Bbt9TEq52DtYs/jYRQ0jbJlYSv91x2iGSHtJ/VKF9OjFr9mO9gMl7s4lc80P+JIXjUKIlzdPVHxWiNiVmX/cg2XkmjC1HUki40tqNHVBIs2krHkGiZXqOfm/ilgOmFmRBpupjpPMJpWC0Rva5aPI62sa5woRT7p5TbwLsdjKQxf0/613WY+zbyqz3Y+qpcoMwHuSLRDKVuMWb+GDrd6cKBqSY05vo6GFZAnBrDVDT1o2rX50sqq0vykoU35Rr9XONMx4fnNgkPiWRWsG5nLfW6Z2gbmaTHEO7b8FcxtZEBpIwhql/WQqU/TL2qfiOjJkMtsijwd7wSb+7zkW7zXTV6C4Ywkh/2kVU2hUjhjYoNyTBExmLRiX6p6Jt/ShRDse0ar4G1SgMAfurgbY9k2t2vzp3B+Qlzt/rjx7Fn1BBUdXUNa3Y5EfEVWs3zNlS2af58l5uHhr8MQ7ZZymrlPATkNFl7hF5NNdQKPIqid2m/J2/F31Oh+KglNxkDdmfL2+56ZSC/RczjQxFW/ioWZM1tUdq6AsMC6+hjI99ThrlFZure34ufFdTcqxYtkN6abHjTU7nGhIafvUGr14pdFDD7yOm2d8+qg62WxMP2oz1Mj5D+427bnTOurxvsWolU0N5zGjxVvJQGIfgruqt0="
  file:
    - bin/appix-mac
    - bin/appix-linux
    - bin/appix.exe
  on:
    repo: Travix-International/appix
    tags: true # The deployment happens only if the commit has a tag.

notifications:
  email: false
