# We need an OSX agent. This is a bit slow, but that's the only system that can properly cross-compile appix for all
# three environments.
os: osx

osx_image: xcode8.3

language: go

go:
- tip # The latest version of Go.

script:
- "./build.sh"

deploy:
  provider: releases
  skip_cleanup: true # Important, otherwise the build output would be purged.
  api_key:
    secure: lFGBaFkQWNzI8t1szyc1EyaqHx1fj3zHhqmdPytVuhDIWEAgrzMrTHte4nhNv8ypMS+xQjARZqCVcJJuCShhbU4BiMdSkZbLD5BxEDgqq5OdX5wQSU9t0xneWYoOAawTdLJVzpWBcObH7pDBPHQNwbiMhwrQ4O6IlRc+gOztE0Djoi7p5IwjKr6IKF5rHnbedMIpsivIbO6STeXUnR/PjKXu0QQzZty/NVYCISRvVB2by/6SLbYDDjrdY04I0RbmDhZnaS3VV1oR2AXtg9mu+5FFvfGFAuWMcEGfkiG4H3JWwSPlv5BY0gxYMMagiGU/0Sq1Qu/39/XevKgItbQ0J7lbI67O76O3jHF1Hszv0SXV1F5hlEX62YIL8qvGKBq5D6imir1Wy99FfpEjlh4b2WyfeW+d5Ku0EVKowp4eBGF1QJ5bjW3P+HmbRNpNmwO1fpgciyfIXciBUfI+vsfV1G67cwNm0C04TZyH3rNVWx/9HVdqqkPsMjn0yHhcBEm4oVKV4YGpKcm9B9LqDvNDCfvhhupUl8fQSJ1lDPDIYWB7yvXYtEIMFgtkaNv0XZ2a7wS1BpV1ve04nyMJHB/pvDTpvT8kzKmHoILOEmXaBfxHcuvFnVZ1+QB0kRuggqSzETntd6y+YRx3jIaTubFGs8yMj2jWIsM0cZLMcT4qsCY=
  file:
    - bin/appix-mac
    - bin/appix-linux
    - bin/appix.exe
  on:
    repo: Travix-International/appix
    tags: true # The deployment happens only if the commit has a tag.

notifications:
  email: false
